leftnav:
- identifier: external--376293363-1697542772389
  name: The Toolkit
  url: https://environmentalsolutions.mit.edu/climate-justice-instructional-toolkit/
  weight: 10
- identifier: 2ed2f0a0-195d-4472-b20a-157fa2166a25
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
